### ISSUE TITLE
Circular references when adding a Program Rule for ETA program

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/Advanced-Metadata-Export#4]
Redmine issue: 
http://who-dev.essi.upc.edu:8083/issues/1247

You can check with any of the ETA program Program Rules. I activated all the options related to program rule object in the admin menu, and all other models related to the program rule were still added

**Comment by SferaDev** [comment]
Confirmed the bug on extranet/dhis2-dev.

I've tried to reproduce the bug and it's gone as a side effect of #5.

Attached is the debug log of an example: ANGqrDKt33c - Hide ETA_Age and DOB. In the log we can verify that there seem to be no circular references anymore.

[localhost-1550187640811.log](https://github.com/EyeSeeTea/Advanced-Metadata-Export/files/2867232/localhost-1550187640811.log)
